Update tmux-run script

diff --git a/bin/tmux-run b/bin/tmux-run
--- a/bin/tmux-run
+++ b/bin/tmux-run
@@ -1,36 +1,55 @@
 #!/usr/bin/env bash
 
-POSITION="right"
-while [ $# -gt 0 ]; do
+target="right"
+
+while [[ $# -gt 0 ]]; do
   case $1 in
-    --) break;;
-    -*) POSITION="${1#-}" ;;
-    *) NAME="$1"; shift; break;;
+    -t|--target)
+      target="$2"
+      shift 2
+      ;;
+    -h|--help)
+      # Print help
+      echo "Usage: tmux-run -t [right|bottom|top|window|popup] name -- command".
+      exit 0
+      ;;
+    --)
+      shift
+      break
+      ;;
+    -*|--*)
+      echo "${0}: invalid option -- '${1}'"
+      exit 1
+      ;;
+    *)
+      positional_args+=("$1")
+      shift
+      ;;
   esac
-  shift
 done
 
+name=${positional_args[0]}
+
 if [ $# -gt 0 ]; then
-  shift
-  CMD="$@"
+  cmd="$@"
 else
-  CMD="$NAME"
+  cmd="$name"
 fi
 
-if [ "$POSITION" = "popup" ]; then
+if [ "$target" = "popup" ]; then
   tmux if-shell -F '#{e|==:#{N/s:popup},0}' 'new-session -d -s popup "tmux source-file ~/.dotfiles/tmux/sessions/popup.tmux.conf"'
-  tmux if-shell "tmux select-window -t popup:$NAME" "" "new-window -t popup: -c \"#{pane_current_path}\" -n $NAME $CMD"
+  tmux if-shell "tmux select-window -t popup:$name" "" "new-window -t popup: -c \"#{pane_current_path}\" -n $name $cmd"
   tmux display-popup -b rounded -h 90% -w 85% -E "tmux attach-session -t popup"
-elif [ "$POSITION" = "window" ]; then
-  tmux if-shell "tmux select-window -t $NAME" "" "new-window -c \"#{pane_current_path}\" -n $NAME $CMD"
-elif [ "$POSITION" = "top" ]; then
-  tmux display-popup -b rounded -h 24 -w 80 -x R -y W -d '#{pane_current_path}' -T "#[fg=orange]❀ $NAME" -E "$CMD"
-elif [ "$POSITION" = "bottom" ]; then
+elif [ "$target" = "window" ]; then
+  tmux if-shell "tmux select-window -t $name" "" "new-window -c \"#{pane_current_path}\" -n $name $cmd"
+elif [ "$target" = "top" ]; then
+  tmux display-popup -b rounded -h 24 -w 80 -x R -y W -d '#{pane_current_path}' -T "#[fg=orange]❀ $name" -E "$cmd"
+elif [ "$target" = "bottom" ]; then
   tmux if-shell -F '#{e|==:#{window_panes},1}' 'split-window -d -v -l 15 -c "#{pane_current_path}"' 'respawn-pane -k -t "{bottom}" -c "#{pane_current_path}'
   tmux run-shell 'sleep 0.2'
-  tmux send-keys -t "{$POSITION}" "$*" Enter
+  tmux send-keys -t "{$target}" "$cmd" Enter
 else
   tmux if-shell -F '#{e|==:#{window_panes},1}' 'split-window -d -h -l 80 -c "#{pane_current_path}"' 'respawn-pane -k -t "{right}" -c "#{pane_current_path}'
   tmux run-shell 'sleep 0.2'
-  tmux send-keys -t "{$POSITION}" "$*" Enter
+  tmux send-keys -t "{$target}" "$cmd" Enter
 fi
